server:
  port: 8000
  servlet:
    # 应用的访问路径
    context-path: /exhibitionbk

mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.cuit.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  plus:
    global-config:
      db-config:
        id-type: assign_id
        id-worker:
          datacenter-id: 0 # 数据中心 ID 设置为 0
          worker-id: 0 # 工作机器 ID 设置为 0

# PageHelper分页插件
pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

jwt:
  expire: 36000 #秒
  secret: jwt+shiro
  refreshtoken-expire: 36000 #秒

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exhibition_mag?characterEncoding=utf-8
    username: 数据库用户名
    password: 数据库密码
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器端口号
    port: 6379
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    lettuce:
      pool:
        # 最大阻塞等待时间，负数表示没有限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中最大连接数，负数表示没有限制
        max-active: 20
    # 设置密码
    password: 没有就不填

  # 邮箱相关
  mail:
    port: 465
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
    host: smtp.qq.com
    username: 填你的qq邮箱
    # 授权密码， 非邮箱密码，授权码是用于登录第三方邮件客户端的专用密码。
    password: 填你的qq邮箱POP3服务密码
    nickname: 会展管理中心
    from: 填你的qq邮箱

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

Exhibition:
  path: E://Exhibition//sys-author//src//main//resources//static//img

Image:
  path: Oss图片访问路径

Salt:
  value: 自定义盐值

alipay:
  appId: 沙箱支付宝appid
  appPrivateKey: 私钥
  alipayPublicKey: 公钥
  notifyUrl: 内网穿透natapp访问路径
